// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/policy/v1/policy.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/in-toto/attestation/go/v1"
	v11 "github.com/policylabs/signer/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicySet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the policySet identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Meta holds the PolicySet metadata information
	Meta *PolicySetMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Common groups the common data elements to be share by all the
	// policies in the set.
	Common *PolicySetCommon `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	// Policies is the list of policies grouped in the PolicySet
	Policies []*Policy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	// Chain is the evidence chain to compute a set of subjects to which
	// all the policies will apply.
	Chain []*ChainLink `protobuf:"bytes,5,rep,name=chain,proto3" json:"chain,omitempty"`
	// PolicyGroup definitions
	Groups        []*PolicyGroup `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySet) Reset() {
	*x = PolicySet{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySet) ProtoMessage() {}

func (x *PolicySet) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySet.ProtoReflect.Descriptor instead.
func (*PolicySet) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicySet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicySet) GetMeta() *PolicySetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicySet) GetCommon() *PolicySetCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PolicySet) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicySet) GetChain() []*ChainLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *PolicySet) GetGroups() []*PolicyGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// PolicySetMeta captures data about a policy set.
type PolicySetMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime to use as default for policies. Defines the runtime and version
	// to use when evaluating policy code. Defaults to cel/v0 in AMPEL.
	Runtime string `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Human description of the PolicySet
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Expiration date. When set, the policyset will fail if the expiration date
	// has passed.
	Expiration *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Version of the PolicySet.
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Enforce marks if the policy engine returns FAIL or SOFTFAIL if policies
	// fail. Values "ON"/"OFF", defaults to "ON"
	Enforce string `protobuf:"bytes,5,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Framework references checked by this policy set. The references give
	// meaning to control references in the policies.
	Frameworks []*FrameworkRef `protobuf:"bytes,6,rep,name=frameworks,proto3" json:"frameworks,omitempty"`
	// Origin of the policyset's data, recorded when compiled.
	Origin *v1.ResourceDescriptor `protobuf:"bytes,7,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	// PolicySet changelog, records the changes in the policy code
	Changelog []*ChangeLog `protobuf:"bytes,8,rep,name=changelog,proto3" json:"changelog,omitempty"`
	// Name of the policy set (single line string)
	Name          string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySetMeta) Reset() {
	*x = PolicySetMeta{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySetMeta) ProtoMessage() {}

func (x *PolicySetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySetMeta.ProtoReflect.Descriptor instead.
func (*PolicySetMeta) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySetMeta) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *PolicySetMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicySetMeta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *PolicySetMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicySetMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *PolicySetMeta) GetFrameworks() []*FrameworkRef {
	if x != nil {
		return x.Frameworks
	}
	return nil
}

func (x *PolicySetMeta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PolicySetMeta) GetChangelog() []*ChangeLog {
	if x != nil {
		return x.Changelog
	}
	return nil
}

func (x *PolicySetMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FrameworkRef is a reference to a security framework. The reference binds
// the controls tested by each the policy to the the framework definition.
type FrameworkRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String identifier for the framework
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Security framework name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Link to the framework definition
	Definition    *v1.ResourceDescriptor `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameworkRef) Reset() {
	*x = FrameworkRef{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkRef) ProtoMessage() {}

func (x *FrameworkRef) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkRef.ProtoReflect.Descriptor instead.
func (*FrameworkRef) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *FrameworkRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FrameworkRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FrameworkRef) GetDefinition() *v1.ResourceDescriptor {
	if x != nil {
		return x.Definition
	}
	return nil
}

type PolicySetCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*v11.Identity        `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	References    []*PolicyRef           `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	Context       map[string]*ContextVal `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySetCommon) Reset() {
	*x = PolicySetCommon{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySetCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySetCommon) ProtoMessage() {}

func (x *PolicySetCommon) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySetCommon.ProtoReflect.Descriptor instead.
func (*PolicySetCommon) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicySetCommon) GetIdentities() []*v11.Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *PolicySetCommon) GetReferences() []*PolicyRef {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *PolicySetCommon) GetContext() map[string]*ContextVal {
	if x != nil {
		return x.Context
	}
	return nil
}

type Policy struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source       *PolicyRef             `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Meta         *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Context      map[string]*ContextVal `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chain        []*ChainLink           `protobuf:"bytes,5,rep,name=chain,proto3" json:"chain,omitempty"`
	Identities   []*v11.Identity        `protobuf:"bytes,6,rep,name=identities,proto3" json:"identities,omitempty"`
	Predicates   *PredicateSpec         `protobuf:"bytes,7,opt,name=predicates,proto3" json:"predicates,omitempty"`
	Transformers []*Transformer         `protobuf:"bytes,8,rep,name=transformers,proto3" json:"transformers,omitempty"`
	Tenets       []*Tenet               `protobuf:"bytes,9,rep,name=tenets,proto3" json:"tenets,omitempty"`
	// When gates the evaluation of the policy (see When). It may be set on a
	// policy referencing another to gate the referenced policy.
	When          *When `protobuf:"bytes,10,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetSource() *PolicyRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Policy) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Policy) GetContext() map[string]*ContextVal {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Policy) GetChain() []*ChainLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Policy) GetIdentities() []*v11.Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *Policy) GetPredicates() *PredicateSpec {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *Policy) GetTransformers() []*Transformer {
	if x != nil {
		return x.Transformers
	}
	return nil
}

func (x *Policy) GetTenets() []*Tenet {
	if x != nil {
		return x.Tenets
	}
	return nil
}

func (x *Policy) GetWhen() *When {
	if x != nil {
		return x.When
	}
	return nil
}

type PolicyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Identity      *v11.Identity          `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Location      *v1.ResourceDescriptor `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRef) Reset() {
	*x = PolicyRef{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRef) ProtoMessage() {}

func (x *PolicyRef) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRef.ProtoReflect.Descriptor instead.
func (*PolicyRef) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyRef) GetIdentity() *v11.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PolicyRef) GetLocation() *v1.ResourceDescriptor {
	if x != nil {
		return x.Location
	}
	return nil
}

type ChainLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ChainLink_Predicate
	Source        isChainLink_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainLink) Reset() {
	*x = ChainLink{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainLink) ProtoMessage() {}

func (x *ChainLink) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainLink.ProtoReflect.Descriptor instead.
func (*ChainLink) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ChainLink) GetSource() isChainLink_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ChainLink) GetPredicate() *ChainedPredicate {
	if x != nil {
		if x, ok := x.Source.(*ChainLink_Predicate); ok {
			return x.Predicate
		}
	}
	return nil
}

type isChainLink_Source interface {
	isChainLink_Source()
}

type ChainLink_Predicate struct {
	Predicate *ChainedPredicate `protobuf:"bytes,1,opt,name=predicate,proto3,oneof"` // ChainedOutput output = 2;
}

func (*ChainLink_Predicate) isChainLink_Source() {}

// Meta contains information about the policy itself
type Meta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime identifier. Defines the runtime and version. Eg cel/v0
	Runtime string `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Human readable description o the policy.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// AssertMode. Controls if one tenet or all must pass for the policy to pass.
	AssertMode string `protobuf:"bytes,3,opt,name=assert_mode,json=assertMode,proto3" json:"assert_mode,omitempty"`
	// Control references. Reference to framework controls the policy verifies.
	Controls []*Control `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	// Version is an integer marking the policy version. Optional.
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// Enforce controls if a FAILED policy returns FAILED or SOFTFAIL. Values "Y"/"N"
	Enforce string `protobuf:"bytes,6,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Expiration date. Policies can expire as defined by this optional field.
	Expiration *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	// Origin captures the origin of a policy when the compiler gathers its data.
	Origin *v1.ResourceDescriptor `protobuf:"bytes,8,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	// Policy changelog
	Changelog []*ChangeLog `protobuf:"bytes,9,rep,name=changelog,proto3" json:"changelog,omitempty"`
	// Name of the policy (single line string)
	Name          string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *Meta) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Meta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meta) GetAssertMode() string {
	if x != nil {
		return x.AssertMode
	}
	return ""
}

func (x *Meta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *Meta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Meta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *Meta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *Meta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Meta) GetChangelog() []*ChangeLog {
	if x != nil {
		return x.Changelog
	}
	return nil
}

func (x *Meta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ChangeLog records a change in the policy or policyset code.
type ChangeLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changelog message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Recorded date of the change
	Date *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3,oneof" json:"date,omitempty"`
	// Version number when the change was introduced
	Version       *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeLog) Reset() {
	*x = ChangeLog{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLog) ProtoMessage() {}

func (x *ChangeLog) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLog.ProtoReflect.Descriptor instead.
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChangeLog) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ChangeLog) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

// Control is a mapping tying the policy to an framework control
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Control ID string.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human readable description of the control
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Framework identifier string
	Framework string `protobuf:"bytes,3,opt,name=framework,proto3" json:"framework,omitempty"`
	// Control class/family within its framework
	Class string `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	// Subitem identifier of control checks
	Item          string `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *Control) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Control) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Control) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Control) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Control) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

// When gates the evaluation of a Policy or a PolicyBlock on a condition. The
// expression is evaluated before any evidence is fetched, against the subject
// under evaluation, the context values in scope and the runtime plugins;
// predicates are not available to it. When it yields false the element is
// skipped: it is reported as SKIPPED and does not count towards the status of
// the PolicySet or PolicyGroup containing it. An empty `when` (or an empty
// expression) always evaluates. PolicySets and PolicyGroups are containers
// and carry no condition of their own.
//
// Context values used by the expression MUST be declared in the context
// definitions in scope (the policy's own or those it inherits from the
// common block of its PolicySet or PolicyGroup); the runtime evaluating the
// expression fails on values that are not defined.
type When struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression is an evaluator-language snippet that must yield a boolean.
	// Empty means the element always evaluates.
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Runtime selects the evaluator used to resolve `expression`. When empty,
	// the runtime defined for the policy (or its parent) is used.
	Runtime       string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *When) Reset() {
	*x = When{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *When) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*When) ProtoMessage() {}

func (x *When) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use When.ProtoReflect.Descriptor instead.
func (*When) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *When) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *When) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// ContextVal defines a contextual value needed by a policy. Context values
// are defined from external sources at runtime and if required will cause the
// policy to fail if unset.
type ContextVal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data type of the context value. Enforced values are "string", "int", "bool", "float".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Required flag. If set to true, policies will not evaluate if the context value is not set.
	Required *bool `protobuf:"varint,2,opt,name=required,proto3,oneof" json:"required,omitempty"`
	// Value field. If the ContextVal is typed, the data should be castable to the type defined in Type.
	Value *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// Default value when ContextVal is not set. If the ContextVal is typed, the
	// default value should be castable into the type defined in type
	Default *structpb.Value `protobuf:"bytes,4,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Human readable description of the ContextValue
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Expression is an evaluator-language snippet resolved at evaluation time
	// to produce the context value dynamically (e.g. from the subject under
	// evaluation). It is mutually exclusive with both `value` and `default`,
	// since an expression is a burned-in computation with no static fallback.
	Expression *string `protobuf:"bytes,6,opt,name=expression,proto3,oneof" json:"expression,omitempty"`
	// Runtime selects the evaluator used to resolve `expression`. When empty,
	// the policy's default runtime is used.
	Runtime       *string `protobuf:"bytes,7,opt,name=runtime,proto3,oneof" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextVal) Reset() {
	*x = ContextVal{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextVal) ProtoMessage() {}

func (x *ContextVal) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextVal.ProtoReflect.Descriptor instead.
func (*ContextVal) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *ContextVal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContextVal) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *ContextVal) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContextVal) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ContextVal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ContextVal) GetExpression() string {
	if x != nil && x.Expression != nil {
		return *x.Expression
	}
	return ""
}

func (x *ContextVal) GetRuntime() string {
	if x != nil && x.Runtime != nil {
		return *x.Runtime
	}
	return ""
}

// The error structure is returned when a policy is evaluated successfully but
// the evaluation fails.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message contains the condition that failed to be met, causing the policy to fail.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Guidance is an optional text record that is surfaced to the user with
	// suggestions to make the policy evaluation pass.
	Guidance      string `protobuf:"bytes,2,opt,name=guidance,proto3" json:"guidance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

// Transformer loads and configures a transformer to operate on the policy data
// before the predicates reach the runtime. Transformers are loaded by their id
// string and need to be compiled into the AMPEL engine.
type Transformer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transformer identifier string, currently only internal:ID ids are recognized.
	// Optional @vM or @vM.m suffix selects a transformer version.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Configuration struct for the transformer, implementation specific
	Config        *structpb.Struct `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transformer) Reset() {
	*x = Transformer{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transformer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transformer) ProtoMessage() {}

func (x *Transformer) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transformer.ProtoReflect.Descriptor instead.
func (*Transformer) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{13}
}

func (x *Transformer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transformer) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type PredicateSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredicateSpec) Reset() {
	*x = PredicateSpec{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredicateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicateSpec) ProtoMessage() {}

func (x *PredicateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicateSpec.ProtoReflect.Descriptor instead.
func (*PredicateSpec) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{14}
}

func (x *PredicateSpec) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *PredicateSpec) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Tenet is the foundational condition of a policy. It is held as a truth that
// needs to be proven for the policy to pass.
type Tenet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Runtime       string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Predicates    *PredicateSpec         `protobuf:"bytes,4,opt,name=predicates,proto3" json:"predicates,omitempty"`
	Outputs       map[string]*Output     `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Assessment    *Assessment            `protobuf:"bytes,8,opt,name=assessment,proto3" json:"assessment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenet) Reset() {
	*x = Tenet{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenet) ProtoMessage() {}

func (x *Tenet) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenet.ProtoReflect.Descriptor instead.
func (*Tenet) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{15}
}

func (x *Tenet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenet) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Tenet) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Tenet) GetPredicates() *PredicateSpec {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *Tenet) GetOutputs() map[string]*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Tenet) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Tenet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tenet) GetAssessment() *Assessment {
	if x != nil {
		return x.Assessment
	}
	return nil
}

type ChainedOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        string                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Tenet         string                 `protobuf:"bytes,2,opt,name=tenet,proto3" json:"tenet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainedOutput) Reset() {
	*x = ChainedOutput{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainedOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainedOutput) ProtoMessage() {}

func (x *ChainedOutput) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainedOutput.ProtoReflect.Descriptor instead.
func (*ChainedOutput) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{16}
}

func (x *ChainedOutput) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *ChainedOutput) GetTenet() string {
	if x != nil {
		return x.Tenet
	}
	return ""
}

// ChainedPredicate links a subject to another by extracting data from
// attestations of the first. The spec requires a `selector` to be executed
// by the specified `runtime` on an attestation of type `type`.
//
// The selector exec is expected to return either a hash string or a struct that
// looks like an in-toto resource descriptor which becomes the new effective
// subject during the evaluation.
type ChainedPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Identities    []*v11.Identity        `protobuf:"bytes,5,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainedPredicate) Reset() {
	*x = ChainedPredicate{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainedPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainedPredicate) ProtoMessage() {}

func (x *ChainedPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainedPredicate.ProtoReflect.Descriptor instead.
func (*ChainedPredicate) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{17}
}

func (x *ChainedPredicate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChainedPredicate) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ChainedPredicate) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ChainedPredicate) GetIdentities() []*v11.Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type Assessment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assessment) Reset() {
	*x = Assessment{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assessment) ProtoMessage() {}

func (x *Assessment) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assessment.ProtoReflect.Descriptor instead.
func (*Assessment) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{18}
}

func (x *Assessment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{19}
}

func (x *Output) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Output) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// PolicyGroup captures the structure of a policy set in a
type PolicyGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Group metadata
	Meta *PolicyGroupMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Common groups the common data elements to be share by all the
	// policies in the group.
	Common *PolicySetCommon `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	// Group reference
	Source *PolicyGroupRef `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Policy blocks modeling the group begaviour.
	Blocks []*PolicyBlock `protobuf:"bytes,5,rep,name=blocks,proto3" json:"blocks,omitempty"`
	// Chain is the evidence chain to compute a set of subjects to which
	// PolicyGroup will apply.
	Chain         []*ChainLink `protobuf:"bytes,6,rep,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroup) Reset() {
	*x = PolicyGroup{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroup) ProtoMessage() {}

func (x *PolicyGroup) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroup.ProtoReflect.Descriptor instead.
func (*PolicyGroup) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{20}
}

func (x *PolicyGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyGroup) GetMeta() *PolicyGroupMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicyGroup) GetCommon() *PolicySetCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PolicyGroup) GetSource() *PolicyGroupRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PolicyGroup) GetBlocks() []*PolicyBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *PolicyGroup) GetChain() []*ChainLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

// PolicyBlock groups policies in the PolicySet to apply properties to more
// than one policy at once.
type PolicyBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID string identifying the block
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Meta contains the metadata describing the
	Meta *PolicyBlockMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Policies is the list of policies grouped in the block
	Policies []*Policy `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	// When gates the evaluation of the block (see When).
	When          *When `protobuf:"bytes,4,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBlock) Reset() {
	*x = PolicyBlock{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBlock) ProtoMessage() {}

func (x *PolicyBlock) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBlock.ProtoReflect.Descriptor instead.
func (*PolicyBlock) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{21}
}

func (x *PolicyBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyBlock) GetMeta() *PolicyBlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicyBlock) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicyBlock) GetWhen() *When {
	if x != nil {
		return x.When
	}
	return nil
}

// GroupMeta is the metadata definition of a policy group
type PolicyGroupMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the policy block
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Version of the group
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Control fronted by the policy group
	Controls []*Control `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	// Enforce the block (ON or OFF)
	Enforce string `protobuf:"bytes,4,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Expiration date of the policy group
	Expiration *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	// Source of the group data when compiled from remote sources
	Origin *v1.ResourceDescriptor `protobuf:"bytes,6,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	// Runtime engine identifier. Defaults to cel/v0 in AMPEL.
	Runtime string `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// PolicyGroup changelog
	Changelog []*ChangeLog `protobuf:"bytes,8,rep,name=changelog,proto3" json:"changelog,omitempty"`
	// Assert mode to consider the policy group passing (OR or AND)
	AssertMode string `protobuf:"bytes,9,opt,name=assert_mode,json=assertMode,proto3" json:"assert_mode,omitempty"`
	// Name of the policy group (single line string)
	Name          string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroupMeta) Reset() {
	*x = PolicyGroupMeta{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroupMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroupMeta) ProtoMessage() {}

func (x *PolicyGroupMeta) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroupMeta.ProtoReflect.Descriptor instead.
func (*PolicyGroupMeta) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{22}
}

func (x *PolicyGroupMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyGroupMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyGroupMeta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *PolicyGroupMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *PolicyGroupMeta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *PolicyGroupMeta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PolicyGroupMeta) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *PolicyGroupMeta) GetChangelog() []*ChangeLog {
	if x != nil {
		return x.Changelog
	}
	return nil
}

func (x *PolicyGroupMeta) GetAssertMode() string {
	if x != nil {
		return x.AssertMode
	}
	return ""
}

func (x *PolicyGroupMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PolicyBlockMeta defines the metadata definition of a policy block
type PolicyBlockMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the policy block
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Assert mode to consider the policy block passing (OR or AND)
	AssertMode string `protobuf:"bytes,2,opt,name=assert_mode,json=assertMode,proto3" json:"assert_mode,omitempty"`
	// Enforce the block (ON or OFF)
	Enforce string `protobuf:"bytes,3,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Framework controls fronted by the block
	Controls      []*Control `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBlockMeta) Reset() {
	*x = PolicyBlockMeta{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBlockMeta) ProtoMessage() {}

func (x *PolicyBlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBlockMeta.ProtoReflect.Descriptor instead.
func (*PolicyBlockMeta) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{23}
}

func (x *PolicyBlockMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyBlockMeta) GetAssertMode() string {
	if x != nil {
		return x.AssertMode
	}
	return ""
}

func (x *PolicyBlockMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *PolicyBlockMeta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

// PolicyGroupRef references a group remotely
type PolicyGroupRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pinned version of the group
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Expected identity when the group file is signed
	Identity *v11.Identity `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	// Source location when referenced remotely
	Location      *v1.ResourceDescriptor `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroupRef) Reset() {
	*x = PolicyGroupRef{}
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroupRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroupRef) ProtoMessage() {}

func (x *PolicyGroupRef) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_policy_v1_policy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroupRef.ProtoReflect.Descriptor instead.
func (*PolicyGroupRef) Descriptor() ([]byte, []int) {
	return file_carabiner_policy_v1_policy_proto_rawDescGZIP(), []int{24}
}

func (x *PolicyGroupRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyGroupRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyGroupRef) GetIdentity() *v11.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PolicyGroupRef) GetLocation() *v1.ResourceDescriptor {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_carabiner_policy_v1_policy_proto protoreflect.FileDescriptor

const file_carabiner_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	" carabiner/policy/v1/policy.proto\x12\x13carabiner.policy.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a0in_toto_attestation/v1/resource_descriptor.proto\x1a\"carabiner/signer/v1/identity.proto\"\xba\x02\n" +
	"\tPolicySet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".carabiner.policy.v1.PolicySetMetaR\x04meta\x12<\n" +
	"\x06common\x18\x03 \x01(\v2$.carabiner.policy.v1.PolicySetCommonR\x06common\x127\n" +
	"\bpolicies\x18\x04 \x03(\v2\x1b.carabiner.policy.v1.PolicyR\bpolicies\x124\n" +
	"\x05chain\x18\x05 \x03(\v2\x1e.carabiner.policy.v1.ChainLinkR\x05chain\x128\n" +
	"\x06groups\x18\x06 \x03(\v2 .carabiner.policy.v1.PolicyGroupR\x06groups\"\xb7\x03\n" +
	"\rPolicySetMeta\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x18\n" +
	"\aenforce\x18\x05 \x01(\tR\aenforce\x12A\n" +
	"\n" +
	"frameworks\x18\x06 \x03(\v2!.carabiner.policy.v1.FrameworkRefR\n" +
	"frameworks\x12G\n" +
	"\x06origin\x18\a \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x00R\x06origin\x88\x01\x01\x12<\n" +
	"\tchangelog\x18\b \x03(\v2\x1e.carabiner.policy.v1.ChangeLogR\tchangelog\x12%\n" +
	"\x04name\x18\t \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[^\\n\\r]*$R\x04nameB\t\n" +
	"\a_origin\"~\n" +
	"\fFrameworkRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12J\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\n" +
	"definition\"\xba\x02\n" +
	"\x0fPolicySetCommon\x12=\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x1d.carabiner.signer.v1.IdentityR\n" +
	"identities\x12>\n" +
	"\n" +
	"references\x18\x02 \x03(\v2\x1e.carabiner.policy.v1.PolicyRefR\n" +
	"references\x12K\n" +
	"\acontext\x18\x03 \x03(\v21.carabiner.policy.v1.PolicySetCommon.ContextEntryR\acontext\x1a[\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.carabiner.policy.v1.ContextValR\x05value:\x028\x01\"\x82\x05\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06source\x18\x02 \x01(\v2\x1e.carabiner.policy.v1.PolicyRefR\x06source\x12-\n" +
	"\x04meta\x18\x03 \x01(\v2\x19.carabiner.policy.v1.MetaR\x04meta\x12B\n" +
	"\acontext\x18\x04 \x03(\v2(.carabiner.policy.v1.Policy.ContextEntryR\acontext\x124\n" +
	"\x05chain\x18\x05 \x03(\v2\x1e.carabiner.policy.v1.ChainLinkR\x05chain\x12=\n" +
	"\n" +
	"identities\x18\x06 \x03(\v2\x1d.carabiner.signer.v1.IdentityR\n" +
	"identities\x12B\n" +
	"\n" +
	"predicates\x18\a \x01(\v2\".carabiner.policy.v1.PredicateSpecR\n" +
	"predicates\x12D\n" +
	"\ftransformers\x18\b \x03(\v2 .carabiner.policy.v1.TransformerR\ftransformers\x122\n" +
	"\x06tenets\x18\t \x03(\v2\x1a.carabiner.policy.v1.TenetR\x06tenets\x12-\n" +
	"\x04when\x18\n" +
	" \x01(\v2\x19.carabiner.policy.v1.WhenR\x04when\x1a[\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.carabiner.policy.v1.ContextValR\x05value:\x028\x01\"\xb8\x01\n" +
	"\tPolicyRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x129\n" +
	"\bidentity\x18\x03 \x01(\v2\x1d.carabiner.signer.v1.IdentityR\bidentity\x12F\n" +
	"\blocation\x18\x04 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\blocation\"\\\n" +
	"\tChainLink\x12E\n" +
	"\tpredicate\x18\x01 \x01(\v2%.carabiner.policy.v1.ChainedPredicateH\x00R\tpredicateB\b\n" +
	"\x06source\"\xda\x03\n" +
	"\x04Meta\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassert_mode\x18\x03 \x01(\tR\n" +
	"assertMode\x128\n" +
	"\bcontrols\x18\x04 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x18\n" +
	"\aenforce\x18\x06 \x01(\tR\aenforce\x12?\n" +
	"\n" +
	"expiration\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01\x12G\n" +
	"\x06origin\x18\b \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x01R\x06origin\x88\x01\x01\x12<\n" +
	"\tchangelog\x18\t \x03(\v2\x1e.carabiner.policy.v1.ChangeLogR\tchangelog\x12%\n" +
	"\x04name\x18\n" +
	" \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[^\\n\\r]*$R\x04nameB\r\n" +
	"\v_expirationB\t\n" +
	"\a_origin\"\x8e\x01\n" +
	"\tChangeLog\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x123\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04date\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01B\a\n" +
	"\x05_dateB\n" +
	"\n" +
	"\b_version\"w\n" +
	"\aControl\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tframework\x18\x03 \x01(\tR\tframework\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x12\n" +
	"\x04item\x18\x05 \x01(\tR\x04item\"@\n" +
	"\x04When\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\"\xe4\x02\n" +
	"\n" +
	"ContextVal\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\brequired\x18\x02 \x01(\bH\x00R\brequired\x88\x01\x01\x121\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x01R\x05value\x88\x01\x01\x125\n" +
	"\adefault\x18\x04 \x01(\v2\x16.google.protobuf.ValueH\x02R\adefault\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12#\n" +
	"\n" +
	"expression\x18\x06 \x01(\tH\x04R\n" +
	"expression\x88\x01\x01\x12\x1d\n" +
	"\aruntime\x18\a \x01(\tH\x05R\aruntime\x88\x01\x01B\v\n" +
	"\t_requiredB\b\n" +
	"\x06_valueB\n" +
	"\n" +
	"\b_defaultB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_expressionB\n" +
	"\n" +
	"\b_runtime\"=\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bguidance\x18\x02 \x01(\tR\bguidance\"\x93\x01\n" +
	"\vTransformer\x12C\n" +
	"\x02id\x18\x01 \x01(\tB3\xbaH0r.2,^internal:[-_a-z0-9]+(@v[0-9]+(\\.[0-9]+)?)?$R\x02id\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\";\n" +
	"\rPredicateSpec\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xae\x03\n" +
	"\x05Tenet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12B\n" +
	"\n" +
	"predicates\x18\x04 \x01(\v2\".carabiner.policy.v1.PredicateSpecR\n" +
	"predicates\x12A\n" +
	"\aoutputs\x18\x05 \x03(\v2'.carabiner.policy.v1.Tenet.OutputsEntryR\aoutputs\x120\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.carabiner.policy.v1.ErrorR\x05error\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12?\n" +
	"\n" +
	"assessment\x18\b \x01(\v2\x1f.carabiner.policy.v1.AssessmentR\n" +
	"assessment\x1aW\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.carabiner.policy.v1.OutputR\x05value:\x028\x01\"=\n" +
	"\rChainedOutput\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12\x14\n" +
	"\x05tenet\x18\x02 \x01(\tR\x05tenet\"\x9b\x01\n" +
	"\x10ChainedPredicate\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12=\n" +
	"\n" +
	"identities\x18\x05 \x03(\v2\x1d.carabiner.signer.v1.IdentityR\n" +
	"identities\"&\n" +
	"\n" +
	"Assessment\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"J\n" +
	"\x06Output\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xc2\x02\n" +
	"\vPolicyGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04meta\x18\x02 \x01(\v2$.carabiner.policy.v1.PolicyGroupMetaR\x04meta\x12<\n" +
	"\x06common\x18\x03 \x01(\v2$.carabiner.policy.v1.PolicySetCommonR\x06common\x12;\n" +
	"\x06source\x18\x04 \x01(\v2#.carabiner.policy.v1.PolicyGroupRefR\x06source\x128\n" +
	"\x06blocks\x18\x05 \x03(\v2 .carabiner.policy.v1.PolicyBlockR\x06blocks\x124\n" +
	"\x05chain\x18\x06 \x03(\v2\x1e.carabiner.policy.v1.ChainLinkR\x05chain\"\xbf\x01\n" +
	"\vPolicyBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04meta\x18\x02 \x01(\v2$.carabiner.policy.v1.PolicyBlockMetaR\x04meta\x127\n" +
	"\bpolicies\x18\x03 \x03(\v2\x1b.carabiner.policy.v1.PolicyR\bpolicies\x12-\n" +
	"\x04when\x18\x04 \x01(\v2\x19.carabiner.policy.v1.WhenR\x04when\"\xe5\x03\n" +
	"\x0fPolicyGroupMeta\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\bcontrols\x18\x03 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\x12\x18\n" +
	"\aenforce\x18\x04 \x01(\tR\aenforce\x12?\n" +
	"\n" +
	"expiration\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01\x12G\n" +
	"\x06origin\x18\x06 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x01R\x06origin\x88\x01\x01\x12\x18\n" +
	"\aruntime\x18\a \x01(\tR\aruntime\x12<\n" +
	"\tchangelog\x18\b \x03(\v2\x1e.carabiner.policy.v1.ChangeLogR\tchangelog\x12\x1f\n" +
	"\vassert_mode\x18\t \x01(\tR\n" +
	"assertMode\x12%\n" +
	"\x04name\x18\n" +
	" \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[^\\n\\r]*$R\x04nameB\r\n" +
	"\v_expirationB\t\n" +
	"\a_origin\"\xa8\x01\n" +
	"\x0fPolicyBlockMeta\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassert_mode\x18\x02 \x01(\tR\n" +
	"assertMode\x12\x18\n" +
	"\aenforce\x18\x03 \x01(\tR\aenforce\x128\n" +
	"\bcontrols\x18\x04 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\"\xbd\x01\n" +
	"\x0ePolicyGroupRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x129\n" +
	"\bidentity\x18\x03 \x01(\v2\x1d.carabiner.signer.v1.IdentityR\bidentity\x12F\n" +
	"\blocation\x18\x04 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\blocationB\xb9\x01\n" +
	"\x17com.carabiner.policy.v1B\vPolicyProtoP\x01Z#github.com/policylabs/policy/api/v1\xa2\x02\x03CPX\xaa\x02\x13Carabiner.Policy.V1\xca\x02\x13Carabiner\\Policy\\V1\xe2\x02\x1fCarabiner\\Policy\\V1\\GPBMetadata\xea\x02\x15Carabiner::Policy::V1b\x06proto3"

var (
	file_carabiner_policy_v1_policy_proto_rawDescOnce sync.Once
	file_carabiner_policy_v1_policy_proto_rawDescData []byte
)

func file_carabiner_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_carabiner_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_carabiner_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_policy_v1_policy_proto_rawDesc), len(file_carabiner_policy_v1_policy_proto_rawDesc)))
	})
	return file_carabiner_policy_v1_policy_proto_rawDescData
}

var file_carabiner_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_carabiner_policy_v1_policy_proto_goTypes = []any{
	(*PolicySet)(nil),             // 0: carabiner.policy.v1.PolicySet
	(*PolicySetMeta)(nil),         // 1: carabiner.policy.v1.PolicySetMeta
	(*FrameworkRef)(nil),          // 2: carabiner.policy.v1.FrameworkRef
	(*PolicySetCommon)(nil),       // 3: carabiner.policy.v1.PolicySetCommon
	(*Policy)(nil),                // 4: carabiner.policy.v1.Policy
	(*PolicyRef)(nil),             // 5: carabiner.policy.v1.PolicyRef
	(*ChainLink)(nil),             // 6: carabiner.policy.v1.ChainLink
	(*Meta)(nil),                  // 7: carabiner.policy.v1.Meta
	(*ChangeLog)(nil),             // 8: carabiner.policy.v1.ChangeLog
	(*Control)(nil),               // 9: carabiner.policy.v1.Control
	(*When)(nil),                  // 10: carabiner.policy.v1.When
	(*ContextVal)(nil),            // 11: carabiner.policy.v1.ContextVal
	(*Error)(nil),                 // 12: carabiner.policy.v1.Error
	(*Transformer)(nil),           // 13: carabiner.policy.v1.Transformer
	(*PredicateSpec)(nil),         // 14: carabiner.policy.v1.PredicateSpec
	(*Tenet)(nil),                 // 15: carabiner.policy.v1.Tenet
	(*ChainedOutput)(nil),         // 16: carabiner.policy.v1.ChainedOutput
	(*ChainedPredicate)(nil),      // 17: carabiner.policy.v1.ChainedPredicate
	(*Assessment)(nil),            // 18: carabiner.policy.v1.Assessment
	(*Output)(nil),                // 19: carabiner.policy.v1.Output
	(*PolicyGroup)(nil),           // 20: carabiner.policy.v1.PolicyGroup
	(*PolicyBlock)(nil),           // 21: carabiner.policy.v1.PolicyBlock
	(*PolicyGroupMeta)(nil),       // 22: carabiner.policy.v1.PolicyGroupMeta
	(*PolicyBlockMeta)(nil),       // 23: carabiner.policy.v1.PolicyBlockMeta
	(*PolicyGroupRef)(nil),        // 24: carabiner.policy.v1.PolicyGroupRef
	nil,                           // 25: carabiner.policy.v1.PolicySetCommon.ContextEntry
	nil,                           // 26: carabiner.policy.v1.Policy.ContextEntry
	nil,                           // 27: carabiner.policy.v1.Tenet.OutputsEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
	(*v1.ResourceDescriptor)(nil), // 29: in_toto_attestation.v1.ResourceDescriptor
	(*v11.Identity)(nil),          // 30: carabiner.signer.v1.Identity
	(*structpb.Value)(nil),        // 31: google.protobuf.Value
	(*structpb.Struct)(nil),       // 32: google.protobuf.Struct
}
var file_carabiner_policy_v1_policy_proto_depIdxs = []int32{
	1,  // 0: carabiner.policy.v1.PolicySet.meta:type_name -> carabiner.policy.v1.PolicySetMeta
	3,  // 1: carabiner.policy.v1.PolicySet.common:type_name -> carabiner.policy.v1.PolicySetCommon
	4,  // 2: carabiner.policy.v1.PolicySet.policies:type_name -> carabiner.policy.v1.Policy
	6,  // 3: carabiner.policy.v1.PolicySet.chain:type_name -> carabiner.policy.v1.ChainLink
	20, // 4: carabiner.policy.v1.PolicySet.groups:type_name -> carabiner.policy.v1.PolicyGroup
	28, // 5: carabiner.policy.v1.PolicySetMeta.expiration:type_name -> google.protobuf.Timestamp
	2,  // 6: carabiner.policy.v1.PolicySetMeta.frameworks:type_name -> carabiner.policy.v1.FrameworkRef
	29, // 7: carabiner.policy.v1.PolicySetMeta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	8,  // 8: carabiner.policy.v1.PolicySetMeta.changelog:type_name -> carabiner.policy.v1.ChangeLog
	29, // 9: carabiner.policy.v1.FrameworkRef.definition:type_name -> in_toto_attestation.v1.ResourceDescriptor
	30, // 10: carabiner.policy.v1.PolicySetCommon.identities:type_name -> carabiner.signer.v1.Identity
	5,  // 11: carabiner.policy.v1.PolicySetCommon.references:type_name -> carabiner.policy.v1.PolicyRef
	25, // 12: carabiner.policy.v1.PolicySetCommon.context:type_name -> carabiner.policy.v1.PolicySetCommon.ContextEntry
	5,  // 13: carabiner.policy.v1.Policy.source:type_name -> carabiner.policy.v1.PolicyRef
	7,  // 14: carabiner.policy.v1.Policy.meta:type_name -> carabiner.policy.v1.Meta
	26, // 15: carabiner.policy.v1.Policy.context:type_name -> carabiner.policy.v1.Policy.ContextEntry
	6,  // 16: carabiner.policy.v1.Policy.chain:type_name -> carabiner.policy.v1.ChainLink
	30, // 17: carabiner.policy.v1.Policy.identities:type_name -> carabiner.signer.v1.Identity
	14, // 18: carabiner.policy.v1.Policy.predicates:type_name -> carabiner.policy.v1.PredicateSpec
	13, // 19: carabiner.policy.v1.Policy.transformers:type_name -> carabiner.policy.v1.Transformer
	15, // 20: carabiner.policy.v1.Policy.tenets:type_name -> carabiner.policy.v1.Tenet
	10, // 21: carabiner.policy.v1.Policy.when:type_name -> carabiner.policy.v1.When
	30, // 22: carabiner.policy.v1.PolicyRef.identity:type_name -> carabiner.signer.v1.Identity
	29, // 23: carabiner.policy.v1.PolicyRef.location:type_name -> in_toto_attestation.v1.ResourceDescriptor
	17, // 24: carabiner.policy.v1.ChainLink.predicate:type_name -> carabiner.policy.v1.ChainedPredicate
	9,  // 25: carabiner.policy.v1.Meta.controls:type_name -> carabiner.policy.v1.Control
	28, // 26: carabiner.policy.v1.Meta.expiration:type_name -> google.protobuf.Timestamp
	29, // 27: carabiner.policy.v1.Meta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	8,  // 28: carabiner.policy.v1.Meta.changelog:type_name -> carabiner.policy.v1.ChangeLog
	28, // 29: carabiner.policy.v1.ChangeLog.date:type_name -> google.protobuf.Timestamp
	31, // 30: carabiner.policy.v1.ContextVal.value:type_name -> google.protobuf.Value
	31, // 31: carabiner.policy.v1.ContextVal.default:type_name -> google.protobuf.Value
	32, // 32: carabiner.policy.v1.Transformer.config:type_name -> google.protobuf.Struct
	14, // 33: carabiner.policy.v1.Tenet.predicates:type_name -> carabiner.policy.v1.PredicateSpec
	27, // 34: carabiner.policy.v1.Tenet.outputs:type_name -> carabiner.policy.v1.Tenet.OutputsEntry
	12, // 35: carabiner.policy.v1.Tenet.error:type_name -> carabiner.policy.v1.Error
	18, // 36: carabiner.policy.v1.Tenet.assessment:type_name -> carabiner.policy.v1.Assessment
	30, // 37: carabiner.policy.v1.ChainedPredicate.identities:type_name -> carabiner.signer.v1.Identity
	31, // 38: carabiner.policy.v1.Output.value:type_name -> google.protobuf.Value
	22, // 39: carabiner.policy.v1.PolicyGroup.meta:type_name -> carabiner.policy.v1.PolicyGroupMeta
	3,  // 40: carabiner.policy.v1.PolicyGroup.common:type_name -> carabiner.policy.v1.PolicySetCommon
	24, // 41: carabiner.policy.v1.PolicyGroup.source:type_name -> carabiner.policy.v1.PolicyGroupRef
	21, // 42: carabiner.policy.v1.PolicyGroup.blocks:type_name -> carabiner.policy.v1.PolicyBlock
	6,  // 43: carabiner.policy.v1.PolicyGroup.chain:type_name -> carabiner.policy.v1.ChainLink
	23, // 44: carabiner.policy.v1.PolicyBlock.meta:type_name -> carabiner.policy.v1.PolicyBlockMeta
	4,  // 45: carabiner.policy.v1.PolicyBlock.policies:type_name -> carabiner.policy.v1.Policy
	10, // 46: carabiner.policy.v1.PolicyBlock.when:type_name -> carabiner.policy.v1.When
	9,  // 47: carabiner.policy.v1.PolicyGroupMeta.controls:type_name -> carabiner.policy.v1.Control
	28, // 48: carabiner.policy.v1.PolicyGroupMeta.expiration:type_name -> google.protobuf.Timestamp
	29, // 49: carabiner.policy.v1.PolicyGroupMeta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	8,  // 50: carabiner.policy.v1.PolicyGroupMeta.changelog:type_name -> carabiner.policy.v1.ChangeLog
	9,  // 51: carabiner.policy.v1.PolicyBlockMeta.controls:type_name -> carabiner.policy.v1.Control
	30, // 52: carabiner.policy.v1.PolicyGroupRef.identity:type_name -> carabiner.signer.v1.Identity
	29, // 53: carabiner.policy.v1.PolicyGroupRef.location:type_name -> in_toto_attestation.v1.ResourceDescriptor
	11, // 54: carabiner.policy.v1.PolicySetCommon.ContextEntry.value:type_name -> carabiner.policy.v1.ContextVal
	11, // 55: carabiner.policy.v1.Policy.ContextEntry.value:type_name -> carabiner.policy.v1.ContextVal
	19, // 56: carabiner.policy.v1.Tenet.OutputsEntry.value:type_name -> carabiner.policy.v1.Output
	57, // [57:57] is the sub-list for method output_type
	57, // [57:57] is the sub-list for method input_type
	57, // [57:57] is the sub-list for extension type_name
	57, // [57:57] is the sub-list for extension extendee
	0,  // [0:57] is the sub-list for field type_name
}

func init() { file_carabiner_policy_v1_policy_proto_init() }
func file_carabiner_policy_v1_policy_proto_init() {
	if File_carabiner_policy_v1_policy_proto != nil {
		return
	}
	file_carabiner_policy_v1_policy_proto_msgTypes[1].OneofWrappers = []any{}
	file_carabiner_policy_v1_policy_proto_msgTypes[6].OneofWrappers = []any{
		(*ChainLink_Predicate)(nil),
	}
	file_carabiner_policy_v1_policy_proto_msgTypes[7].OneofWrappers = []any{}
	file_carabiner_policy_v1_policy_proto_msgTypes[8].OneofWrappers = []any{}
	file_carabiner_policy_v1_policy_proto_msgTypes[11].OneofWrappers = []any{}
	file_carabiner_policy_v1_policy_proto_msgTypes[13].OneofWrappers = []any{}
	file_carabiner_policy_v1_policy_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_policy_v1_policy_proto_rawDesc), len(file_carabiner_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_carabiner_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_carabiner_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_carabiner_policy_v1_policy_proto = out.File
	file_carabiner_policy_v1_policy_proto_goTypes = nil
	file_carabiner_policy_v1_policy_proto_depIdxs = nil
}
